export enum ConfigKeys {
  DISCORD_BOT_TOKEN = "DISCORD_BOT_TOKEN",
  DISCORD_CLIENT_ID = "DISCORD_CLIENT_ID",
  DISCORD_GUILD_ID = "DISCORD_GUILD_ID",
  RIOT_API_KEY = "RIOT_API_KEY",
  RIOT_API_URL = "RIOT_API_URL",
}
